### ISSUE TITLE
[BUG] regression after #13, cannot find file using filename

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-file#1]
Hello, 
Since the merge #13 , the param $files of the method [receive($files = null)](https://github.com/zendframework/zend-file/blob/master/src/Transfer/Adapter/Http.php#L138)  does not work.

In my example code the file MyFile.txt is not moved.

``` php
$adp = new Http();
            $adp->setDestination($mydest);
            $adp->receive("MyFile.txt");
```

In method [getFiles](https://github.com/zendframework/zend-file/blob/master/src/Transfer/Adapter/AbstractAdapter.php#L1410) the name MyFile.txt is never found [(here)](https://github.com/zendframework/zend-file/blob/master/src/Transfer/Adapter/AbstractAdapter.php#L1438) because 
since the merge #13 was added "MyFile.txt" file name is rename in "phpackXwt_MyFile.txt".

---

Originally posted by @buse974 at https://github.com/zendframework/zend-file/issues/19

**Comment by weierophinney** [comment]
I can confirm this issue, the file upload is broken.


---

Originally posted by @yourithielen at https://github.com/zendframework/zend-file/issues/19#issuecomment-189237346

**Comment by weierophinney** [comment]
Hi,

I am the author of the #13 PR.
As I noted in the comments of the pull request, the goal is to correct the behaviour of Zend_File when multiple files are uploaded with the same name in the same form as they would be moved to the same filepath and only one would be present at the end. (In some cases, if the destination folder is the same for all uploads in the app, the problem will also be present even for several upload from different users, it could be a security issue, see [#22](https://github.com/zendframework/zend-file/issues/22))

But in the case you are presenting, the problem is not my code. 

``` php
$adp = new Http();
            $adp->setDestination($mydest);
            $adp->receive("MyFile.txt");
```

If I'm not mistaking, the argument of the receive method should not be the uploaded file name but the html input name. 

``` php
$adp = new Http();
            $adp->setDestination($mydest);
            $adp->receive("input_name");
```


---

Originally posted by @codisart at https://github.com/zendframework/zend-file/issues/19#issuecomment-206434839

**Comment by weierophinney** [comment]
And I am mistaking !

So I just reread the code behind the receive method and in fact, it should find a file by its name.
I may be onto a fix for this issue, but I don't know what this method should be returning if they are several files with the same name in the request.

Do any one have a suggestion ?


---

Originally posted by @codisart at https://github.com/zendframework/zend-file/issues/19#issuecomment-206762685

**Comment by weierophinney** [comment]
Hi everyone, 

I'd really like to know what you think about this problem.
@weierophinney since you merged the original PR, maybe you got an idea ?


---

Originally posted by @codisart at https://github.com/zendframework/zend-file/issues/19#issuecomment-216484955

**Comment by weierophinney** [comment]
Hi, i had this problem bat solved it to make : 
`$adapter->receive()` for all files
 or
 `$adapter->receive('one_file_name_input_html')` if there is one file on sumission.


---

Originally posted by @fallphenix at https://github.com/zendframework/zend-file/issues/19#issuecomment-238713529

**Comment by weierophinney** [comment]
@localheinz 
Can you look at this?

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-file/issues/19#issuecomment-305713197

**Comment by weierophinney** [comment]
Will do!

---

Originally posted by @localheinz at https://github.com/zendframework/zend-file/issues/19#issuecomment-305715152

**Comment by samsonasik** [comment]
@localheinz do you have a chance to check it?

**Comment by localheinz** [comment]
@samsonasik 

Going to take a 👀 tomorrow!

**Comment by localheinz** [comment]
@samsonasik 

I have never used this component, and seeing that it is deprecated and scheduled for removal, I wonder whether it makes sense to put an effort into fixing this issue.

What do you think?

**Comment by samsonasik** [comment]
I have no idea personally. I guess removal won't happen, probably just deprecated ( or mark as "security only" ). The download in packagist still many:

![20200723_182121](https://user-images.githubusercontent.com/459648/88281371-c31fca00-cd11-11ea-9241-94bab8a59890.jpg)

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
