### ISSUE TITLE
In AbastractAdapter: Interface 'Laminas\I18n\Translator\TranslatorAwareInterface' not found

### ISSUE THREAD

**Issue by Shardj** [laminas/laminas-file#2]
Looks like the namespace for TranslatorAwareInterface has changed, it's now Laminas\Validator\Translator\ not Laminas\I18n\Translator

**Comment by froschdesign** [comment]
> Looks like the namespace for TranslatorAwareInterface has changed, it's now Laminas\Validator\Translator\ not Laminas\I18n\Translator

The classname and namespace is correct. See: https://github.com/laminas/laminas-i18n/blob/ba0375006f7526d86e8d66a255fc197205570667/src/Translator/TranslatorAwareInterface.php#L9-L11

Please recheck that you have installed laminas/laminas-i18n.

**Comment by Shardj** [comment]
Thanks, do you have any idea why laminas/laminas-i18n might not have been installed even though it's a dependency of laminas-file? It's odd, my composer.lock correctly has laminas-il8n listed as a dependency of laminas-file, but I don't have laminas-il8n installed.

**Comment by michalbundyra** [comment]
@Shardj in laminas-file we have laminas-i18n as DEV dependency, so that's why it is not installed, see:
https://github.com/laminas/laminas-file/blob/master/composer.json#L35

**Comment by froschdesign** [comment]
@Shardj 
> Thanks, do you have any idea why laminas/laminas-i18n might not have been installed even though it's a dependency of laminas-file?

laminas-i18n is only a _soft_ dependency for this component. For example the [`ClassFileLocator`](https://docs.laminas.dev/laminas-file/class-file-locator/) does not need any translations.
Therefore it is listed in the suggest section of the Composer file:

https://github.com/laminas/laminas-file/blob/f18ba613b88af4cfb5971b51db083a6bb3fb9751/composer.json#L42-L46
